[build]
target = "/home/noe/linux/rust/target.json"
rustflags = [
    "-Ctarget-cpu=native",
    "--emit=obj",
    "--extern", "kernel",
    "--extern", "alloc",
    "-L", "/home/noe/linux/rust",
    "-Cpanic=abort"
]
